import PDFDocument from 'pdfkit';

const drawHeader = (doc, label) => {
    doc.fontSize(22).font('Helvetica-Bold').text('KISO', 50, 50);
    doc.fontSize(10).font('Helvetica').fillColor('#888').text('Premium Furniture', 50, 76);
    doc.fillColor('#000').fontSize(18).font('Helvetica-Bold').text('SALES REPORT', 400, 50, { align: 'right' });
    doc.fontSize(10).font('Helvetica').fillColor('#444').text(label, 400, 76, { align: 'right' });
    doc.moveTo(50, 100).lineTo(545, 100).stroke('#ddd');
};

const drawSummary = (doc, summary, y) => {
    doc.fontSize(12).font('Helvetica-Bold').fillColor('#000').text('Summary', 50, y);
    y += 20;
    const rows = [
        ['Total Orders', String(summary.totalOrders)],
        ['Total Sales (subtotal)', `Rs. ${summary.totalSales.toLocaleString()}`],
        ['Coupon Deductions', `Rs. ${summary.totalCouponDiscount.toLocaleString()}`],
        ['Item-level Discounts', `Rs. ${summary.totalItemDiscount.toLocaleString()}`],
        ['Wallet Paid', `Rs. ${summary.totalWalletPaid.toLocaleString()}`],
        ['Net Revenue', `Rs. ${summary.totalRevenue.toLocaleString()}`],
        ['Refunds Issued', String(summary.totalRefunds)],
        ['Refund Amount', `Rs. ${summary.totalRefundAmount.toLocaleString()}`]
    ];
    doc.fontSize(10).font('Helvetica').fillColor('#222');
    for (const [label, value] of rows) {
        doc.text(label, 50, y, { width: 240 });
        doc.text(value, 290, y, { width: 200, align: 'right' });
        y += 16;
        doc.moveTo(50, y - 2).lineTo(545, y - 2).stroke('#eee');
    }
    return y + 10;
};

const drawBreakdown = (doc, breakdown, y) => {
    if (!breakdown || breakdown.length === 0) return y;
    doc.fontSize(12).font('Helvetica-Bold').fillColor('#000').text('Daily Breakdown', 50, y);
    y += 18;
    doc.rect(50, y, 495, 22).fill('#f5f5f5');
    doc.fillColor('#000').font('Helvetica-Bold').fontSize(9);
    doc.text('Date', 58, y + 7);
    doc.text('Orders', 200, y + 7, { width: 80, align: 'center' });
    doc.text('Sales', 280, y + 7, { width: 100, align: 'right' });
    doc.text('Coupon', 380, y + 7, { width: 70, align: 'right' });
    doc.text('Revenue', 450, y + 7, { width: 90, align: 'right' });
    y += 26;
    doc.font('Helvetica').fontSize(9).fillColor('#222');
    for (const row of breakdown) {
        if (y > 760) { doc.addPage(); y = 50; }
        doc.text(row._id, 58, y, { width: 140 });
        doc.text(String(row.orders), 200, y, { width: 80, align: 'center' });
        doc.text(`Rs. ${row.sales.toLocaleString()}`, 280, y, { width: 100, align: 'right' });
        doc.text(`Rs. ${(row.couponDiscount || 0).toLocaleString()}`, 380, y, { width: 70, align: 'right' });
        doc.text(`Rs. ${row.revenue.toLocaleString()}`, 450, y, { width: 90, align: 'right' });
        y += 16;
        doc.moveTo(50, y - 2).lineTo(545, y - 2).stroke('#eee');
    }
    return y;
};

export const streamSalesReportPdf = (res, { label, summary, breakdown }) => {
    const filename = `sales-report-${Date.now()}.pdf`;
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename="${filename}"`);

    const doc = new PDFDocument({ margin: 50, size: 'A4' });
    doc.pipe(res);

    drawHeader(doc, label);
    let y = 120;
    y = drawSummary(doc, summary, y);
    drawBreakdown(doc, breakdown, y);

    doc.fontSize(8).font('Helvetica').fillColor('#aaa')
        .text('Generated by KISO Admin', 50, 780, { align: 'center', width: 495 });

    doc.end();
};
